### ISSUE TITLE
feature request: add nvme ssd and emmc module openings

### ISSUE THREAD

**Issue by amazingfate** [hominoids/SBC_Model_Framework#6]
There is a emmc module and M.2 M key at the bottom of board radxa rock5b. It's more convenient to install them from the bottom openings.
For example:
![3a4c96ca3859adefc8db45cd5667156](https://user-images.githubusercontent.com/5022901/197449328-4a219658-5259-47a8-9cfc-14710135a8a8.jpg)

**Comment by hominoids** [comment]
I agree and will add access ports, I just placed the components(emmc and M2) in my last commit but I'm waiting to hear placement corrections.  The Radxa mechanical drawings have issues.  As you most likely saw, I'm working with @gnattu(issue #4) trying to get the other Rockpi5b SBC parameters correct so a case prints correctly in SBC Case Builder.  Unfortunately they don't have a 3D printer and I don't have a rockpi5b so it's taking extra steps and a little longer then normal.   It would be nice to have a verified SBC Model to build cases from so If there is anything you can do and are willing to help, it would be appreciated e.g. print a test case (rockpi5b_shell) and provide any corrections.  Regardless, thanks for the suggestion, I'll will get some openings added soon.

**Comment by amazingfate** [comment]
> I agree and will add access ports, I just placed the components(emmc and M2) in my last commit but I'm waiting to hear placement corrections. The Radxa mechanical drawings have issues. As you most likely saw, I'm working with @gnattu(issue #4) trying to get the other Rockpi5b SBC parameters correct so a case prints correctly in SBC Case Builder. Unfortunately they don't have a 3D printer and I don't have a rockpi5b so it's taking extra steps and a little longer then normal. It would be nice to have a verified SBC Model to build cases from so If there is anything you can do and are willing to help, it would be appreciated e.g. print a test case (rockpi5b_shell) and provide any corrections. Regardless, thanks for the suggestion, I'll will get some openings added soon.

I haven't get a v1.42 board yet. I did forked your framework and printed a case for v1.3 developer edition only according to the cad file provided by radxa. You're right we must print a test case to correct our model because I did encounter some issue that have to use a file to fix the case. Maybe you can share the model to the forum of radxa or discord channel of radxa to find some volunteers.

**Comment by hominoids** [comment]
Yes, I had the same thought of asking in the manufacture forums for all the unverified SBC I don't own.  It's the main problem I have with this project, I don't own all of the SBC I want to include, so it adds challenges to the development and testing.  I'm working on an update of SBC Model Framework that will be a major release and was hoping to get that done before contacting any forums so as not to have to re-due all of the SBC entries again.  Likewise, I need to be available to do the work so contacting them in a timed and organized way is important so I'm not overwhelmed or wasting other peoples time.  I'll leave this open until the access ports entries are complete.

**Comment by hominoids** [comment]
I added a large access port that uses one screw which I believe might work better then two smaller ones.  Other approaches can be added moving forward.  This is included with all the rockpi5b cases listed in the pick menu in SBC Case Builder on the main branch.  The sbc_case_builder_accessories.cfg entry is rockpi5b.  If you don't want something in the group you can temporarily comment it out or create a new accessory set under a new name.  Run get_customizer_values.scad and follow the directions to update the pick-boxes in SBC Case Builder with the new accessory entry.
![rockpi5b_bottom_access_port](https://user-images.githubusercontent.com/37256300/197854440-dcc1b605-a2c0-4300-ae16-3638859744f0.png)
There are also some of other things like the SDcard opening and two trim entries for top standoff locations that have interfering components.  With all the changes now, we seem to be really close to having a working model for good case generation.
